services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=backend,localhost,ciso.wathbahs.com
      - CISO_ASSISTANT_URL=https://ciso.wathbahs.com
      - DJANGO_DEBUG=True
      - AUTH_TOKEN_TTL=7200
      - ATTACHMENT_MAX_SIZE_MB=100
      - ATTACHMENT_MAX_NAME_LENGTH=512
    volumes:
      - ./db:/code/db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:8000/api/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 100s

  huey:
    container_name: huey
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    environment:
      - ALLOWED_HOSTS=backend,localhost,ciso.wathbahs.com
      - CISO_ASSISTANT_URL=https://ciso.wathbahs.com
      - DJANGO_DEBUG=False
      - AUTH_TOKEN_TTL=7200
      - ATTACHMENT_MAX_SIZE_MB=100
      - ATTACHMENT_MAX_NAME_LENGTH=512
    volumes:
      - ./db:/code/db
    entrypoint:
      - /bin/sh
      - -c
      - |
        poetry run python manage.py run_huey -w 2 --scheduler-interval 60

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PUBLIC_BACKEND_API_EXPOSED_URL=https://ciso.wathbahs.com/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
    depends_on:
      backend:
        condition: service_healthy
