# Generated by Django 5.2.9 on 2026-01-21 16:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_remove_organisationobjective_new_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencerevision',
            name='attachment',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='', validators=[core.validators.validate_file_size, core.validators.validate_file_name], verbose_name='Attachment'),
        ),
    ]
