# Generated by Django 5.1 on 2026-02-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_increase_attachment_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='ai_analysis',
            field=models.JSONField(blank=True, help_text='AI-generated entity extraction and analysis results', null=True, verbose_name='AI Analysis'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='ai_analysis_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI analysis was last performed', null=True, verbose_name='AI Analysis Updated At'),
        ),
    ]
