# Generated by Django 5.2.9 on 2026-02-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_aianalysisresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aianalysisresult',
            new_name='core_aianal_applied_6d43b6_idx',
            old_name='core_aianal_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='filesearchtable',
            new_name='core_filese_gemini__0614d6_idx',
            old_name='core_filese_gemini__idx',
        ),
        migrations.RenameIndex(
            model_name='filesearchtable',
            new_name='core_filese_upload__9e2533_idx',
            old_name='core_filese_upload__idx',
        ),
        migrations.AlterField(
            model_name='filesearchtable',
            name='gemini_file_id',
            field=models.CharField(help_text='The file ID returned by Gemini File Search', max_length=255, verbose_name='Gemini File ID'),
        ),
        migrations.AlterField(
            model_name='filesearchtable',
            name='gemini_store_id',
            field=models.CharField(help_text='The File Search Store this file belongs to', max_length=255, verbose_name='Gemini File Search Store ID'),
        ),
        migrations.AlterField(
            model_name='filesearchtable',
            name='operation_id',
            field=models.CharField(blank=True, help_text='The operation ID for tracking upload status', max_length=255, null=True, verbose_name='Gemini Operation ID'),
        ),
    ]
